Repository TeamSobokSobok/Sobok-Android, pull requests merged in 2022-01, with the labels that each got.

#2 Feature/1 init setting
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sobok_android/MainActivity.kt
  app/src/main/java/com/example/sobok_android/di/DataSourceModule.kt
  app/src/main/java/com/example/sobok_android/di/NetworkModule.kt
  app/src/main/java/com/example/sobok_android/di/RepositoryModule.kt
  app/src/main/java/com/example/sobok_android/di/SobokApplication.kt
  app/src/main/java/com/example/sobok_android/di/ViewModelModule.kt
  app/src/main/java/com/example/sobok_android/presentation/base/BindingActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/base/BindingFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: suhyeon, Done

#4 Feature/3 resource view setting
  .github/ISSUE_TEMPLATE.md
  .github/PULLREQUESTTEMPLATE.md
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sobok_android/presentation/view/home/HomeFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/notice/NoticeFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/PillEditActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/PillReceiveActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddCalendarActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddDateFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFinishFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddNameFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddRejectActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddTimeFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/ShareEmptyFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/ShareFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/ShareNameEditActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/request/ShareRequestActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/request/ShareRequestSaveFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/request/ShareRequestSearchFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/splash/SplashActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/user/SignInActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/user/SignUpActivity.kt
  app/src/main/res/font/font_pretendard.xml
  app/src/main/res/font/pretendard_black.otf
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_extra_bold.otf
  app/src/main/res/font/pretendard_extra_light.otf
  app/src/main/res/font/pretendard_light.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semi_bold.otf
  app/src/main/res/font/pretendard_thin.otf
  app/src/main/res/layout/activity_pill_add.xml
  app/src/main/res/layout/activity_pill_add_calendar.xml
  app/src/main/res/layout/activity_pill_add_reject.xml
  app/src/main/res/layout/activity_pill_edit.xml
  app/src/main/res/layout/activity_pill_receive.xml
  app/src/main/res/layout/activity_share_name_edit.xml
  app/src/main/res/layout/activity_share_request.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_pill_add_date.xml
  app/src/main/res/layout/fragment_pill_add_finish.xml
  app/src/main/res/layout/fragment_pill_add_name.xml
  app/src/main/res/layout/fragment_pill_add_time.xml
  app/src/main/res/layout/fragment_share.xml
  app/src/main/res/layout/fragment_share_empty.xml
  app/src/main/res/layout/fragment_share_request_save.xml
  app/src/main/res/layout/fragment_share_request_search.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: suhyeon, Done

#7 [CHORE] #6 - gradle 추가
  app/build.gradle
  build.gradle
Labels: chaeyoung, Done

#8 Feature/5 bottom navigation
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sobok_android/presentation/view/MainActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/home/HomeFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/notice/NoticeFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/ShareFragment.kt
  app/src/main/res/color/selector_bottom_navi.xml
  app/src/main/res/drawable/ic_alarm_active.xml
  app/src/main/res/drawable/ic_alarm_inactive.xml
  app/src/main/res/drawable/ic_home_active.xml
  app/src/main/res/drawable/ic_home_inactive.xml
  app/src/main/res/drawable/ic_plus_active.xml
  app/src/main/res/drawable/ic_plus_inactive.xml
  app/src/main/res/drawable/ic_share_active.xml
  app/src/main/res/drawable/ic_share_inactive.xml
  app/src/main/res/drawable/selector_menu_alarm.xml
  app/src/main/res/drawable/selector_menu_home.xml
  app/src/main/res/drawable/selector_menu_plus.xml
  app/src/main/res/drawable/selector_menu_share.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_share.xml
  app/src/main/res/menu/menu_bottom_navi.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: suhyeon, feat, Done

#21 Feature/6 pill add UI
  app/src/main/res/drawable/ic_close_48.xml
  app/src/main/res/drawable/ic_frame_48.xml
  app/src/main/res/drawable/oval_fill_blue.xml
  app/src/main/res/drawable/oval_fill_orange.xml
  app/src/main/res/drawable/oval_fill_pink.xml
  app/src/main/res/drawable/oval_fill_purple.xml
  app/src/main/res/drawable/oval_fill_red.xml
  app/src/main/res/drawable/rectangle_border_gray.xml
  app/src/main/res/drawable/rectangle_fill_gray100.xml
  app/src/main/res/drawable/rectangle_fill_gray200.xml
  app/src/main/res/drawable/rectangle_fill_lightmint_radius8dp.xml
  app/src/main/res/drawable/rectangle_fill_mint.xml
  app/src/main/res/layout/activity_pill_add.xml
  app/src/main/res/layout/fragment_pill_add_finish.xml
  app/src/main/res/layout/item_pill_add_pill_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍎 채영, In progress, UI, 💊 약추가

#25 Feature/20 pill add bottomsheet
  .idea/misc.xml
  app/src/main/java/com/example/sobok_android/presentation/view/MainActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddBottomSheetFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddInfo.kt
  app/src/main/res/drawable/ic_fill_send.xml
  app/src/main/res/drawable/ic_my_fill_plus.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_pill_add_bottom_sheet.xml
  app/src/main/res/layout/fragment_pill_add_finish.xml
  app/src/main/res/layout/fragment_pill_add_info.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🍎 채영, Done, 💊 약추가

#29 Feature/23 pill add finish page
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sobok_android/data/datasource/pill/pilladd/PillAddDataSource.kt
  app/src/main/java/com/example/sobok_android/data/datasource/pill/pilladd/PillAddLocalDataSource.kt
  app/src/main/java/com/example/sobok_android/data/repository/pill/pilladd/PillAddRepositoryImpl.kt
  app/src/main/java/com/example/sobok_android/domain/model/pill/pilladd/PillListData.kt
  app/src/main/java/com/example/sobok_android/domain/repository/pill/pilladd/PillAddRepository.kt
  app/src/main/java/com/example/sobok_android/presentation/di/DataSourceModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/RepositoryModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/ViewModelModule.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFinishActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/adapter/PillListAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/viewmodel/PillAddViewModel.kt
  app/src/main/java/com/example/sobok_android/util/BindingAdapter.kt
  app/src/main/res/layout/activity_pill_add.xml
  app/src/main/res/layout/activity_pill_add_finish.xml
  app/src/main/res/layout/fragment_pill_add_finish.xml
  app/src/main/res/layout/item_pill_add_pill_info.xml
  app/src/main/res/values/strings.xml
Labels: 🍎 채영, In progress, 💊 약추가

#37 Feature/31 share request
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sobok_android/data/api/ShareService.kt
  app/src/main/java/com/example/sobok_android/data/datasource/share/request/ShareRequestDataSource.kt
  app/src/main/java/com/example/sobok_android/data/datasource/share/request/ShareRequestRemoteDataSource.kt
  app/src/main/java/com/example/sobok_android/data/mapper/ShareRequestMapper.kt
  app/src/main/java/com/example/sobok_android/data/model/response/share/request/ResSearchResultData.kt
  app/src/main/java/com/example/sobok_android/data/model/response/share/request/ResShareRequestSuccessData.kt
  app/src/main/java/com/example/sobok_android/data/repository/share/request/ShareRequestRepositoryImpl.kt
  app/src/main/java/com/example/sobok_android/domain/model/share/request/SearchResultData.kt
  app/src/main/java/com/example/sobok_android/domain/model/share/request/ShareRequestSuccessData.kt
  app/src/main/java/com/example/sobok_android/domain/repository/share/request/ShareRequestRepository.kt
  app/src/main/java/com/example/sobok_android/presentation/di/DataSourceModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/NetworkModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/RepositoryModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/ViewModelModule.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/request/ShareRequestActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/request/ShareRequestSaveFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/request/ShareRequestSearchFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/request/viewmodel/ShareRequestViewModel.kt
  app/src/main/res/drawable-v24/rectangle_border_gray_600_radius_12.xml
  app/src/main/res/drawable/ic_close_dark_48.xml
  app/src/main/res/drawable/ic_illust_oops.xml
  app/src/main/res/drawable/ic_notice.xml
  app/src/main/res/drawable/ic_search_48.xml
  app/src/main/res/drawable/ic_text_close_48.xml
  app/src/main/res/drawable/rectangle_border_gray_300_radius_12.xml
  app/src/main/res/drawable/rectangle_border_pill_color_red_radius_12.xml
  app/src/main/res/drawable/rectangle_fill_gray_100_radius_12.xml
  app/src/main/res/drawable/rectangle_fill_gray_100_radius_8.xml
  app/src/main/res/drawable/selector_share_request_search_bar.xml
  app/src/main/res/layout/activity_share_request.xml
  app/src/main/res/layout/fragment_pill_add_bottom_sheet.xml
  app/src/main/res/layout/fragment_share_request_save.xml
  app/src/main/res/layout/fragment_share_request_search.xml
  app/src/main/res/navigation/nav_graph_share_request.xml
  app/src/main/res/values/strings.xml
Labels: 🍋 수현, feat, Done, UI, 💌 공유, network

#40 Feature/26 notice list
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/sobok_android/data/api/NoticeService.kt
  app/src/main/java/com/example/sobok_android/data/datasource/notice/NoticeDataSource.kt
  app/src/main/java/com/example/sobok_android/data/datasource/notice/NoticeRemoteDataSource.kt
  app/src/main/java/com/example/sobok_android/data/mapper/NoticeMapper.kt
  app/src/main/java/com/example/sobok_android/data/model/response/notice/ResNoticeListData.kt
  app/src/main/java/com/example/sobok_android/data/model/response/share/response/ResSharePillListData.kt
  app/src/main/java/com/example/sobok_android/data/repository/notice/NoticeRepositoryImpl.kt
  app/src/main/java/com/example/sobok_android/domain/model/a.txt
  app/src/main/java/com/example/sobok_android/domain/model/notice/NoticeListData.kt
  app/src/main/java/com/example/sobok_android/domain/repository/notice/NoticeRepository.kt
  app/src/main/java/com/example/sobok_android/presentation/di/DataSourceModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/NetworkModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/RepositoryModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/ViewModelModule.kt
  app/src/main/java/com/example/sobok_android/presentation/view/notice/NoticeFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/notice/NoticeListAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/notice/NoticeListData.kt
  app/src/main/java/com/example/sobok_android/presentation/view/notice/model/NoticeInfoData.kt
  app/src/main/java/com/example/sobok_android/presentation/view/notice/viewmodel/NoticeViewModel.kt
  app/src/main/java/com/example/sobok_android/util/BindingAdapter.kt
  app/src/main/res/drawable/ic_illust_oops.xml
  app/src/main/res/drawable/rectangle_notice_list.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_pill_add_finish.xml
  app/src/main/res/layout/item_notice_list.xml
  app/src/main/res/values/strings.xml
Labels: 🍓 정원, feat, UI, 🔔 알림, network

#50 Feature/9 calendar connect
  app/src/main/java/com/example/sobok_android/data/mapper/CalendarMapper.kt
  app/src/main/java/com/example/sobok_android/data/model/response/home/ResHomePillListData.kt
  app/src/main/java/com/example/sobok_android/presentation/view/calendar/CalendarView.kt
  app/src/main/java/com/example/sobok_android/presentation/view/calendar/adapter/CalendarDateRecyclerViewAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/calendar/adapter/CalendarMonthViewPagerAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/calendar/viewmodel/CalendarViewModel.kt
  app/src/main/java/com/example/sobok_android/presentation/view/home/HomeFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/ShareFragment.kt
  app/src/main/java/com/example/sobok_android/util/DateTimeUtil.kt
  app/src/main/res/drawable/ic_illust_home.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/layout_calendar_top.xml
  app/src/main/res/values/strings.xml
Labels: 🍋 수현, feat, Done, UI, 🏠 홈, 💌 공유, network

#49 Feature/24 pill add one page
  .idea/misc.xml
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFinishFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFormFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/adapter/PillListAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/viewmodel/PillAddViewModel.kt
  app/src/main/java/com/example/sobok_android/util/DateTimeUtil.kt
  app/src/main/res/drawable/rectangle_fill_lightred_radius8dp.xml
  app/src/main/res/layout/fragment_pill_add_bottom_sheet.xml
  app/src/main/res/layout/fragment_pill_add_finish.xml
  app/src/main/res/values/strings.xml
Labels: 🍎 채영, In progress, UI, 💊 약추가
