Repository TeamSobokSobok/Sobok-Android, pull requests merged in 2022-08, with the labels that each got.

#63 [FEAT] 내 정보 & 닉네임 수정 UI
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sobok_android/domain/model/myinfo/MyPillData.kt
  app/src/main/java/com/example/sobok_android/presentation/di/SobokApplication.kt
  app/src/main/java/com/example/sobok_android/presentation/view/home/HomeFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/MyInfoActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/MyNicknameEditActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/adapter/MyPillManageAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/viewmodel/MyInfoViewModel.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/ShareNameEditActivity.kt
  app/src/main/java/com/example/sobok_android/util/ContextExt.kt
  app/src/main/java/com/example/sobok_android/util/CustomSnackBar.kt
  app/src/main/res/color/selector_double_check.xml
  app/src/main/res/drawable/ic_close_48_black.xml
  app/src/main/res/drawable/ic_more_48_black.xml
  app/src/main/res/drawable/ic_notice.xml
  app/src/main/res/drawable/ic_pencil_32_black.xml
  app/src/main/res/drawable/ic_setting_48_black.xml
  app/src/main/res/layout/activity_my_info.xml
  app/src/main/res/layout/activity_my_nickname_edit.xml
  app/src/main/res/layout/activity_share_name_edit.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_my_info_pill.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 🍋 수현, UI

#65 [FEAT] 약추가 바텀네비게이션
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/ktlint.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sobok_android/domain/model/pill/pilladd/PillListData.kt
  app/src/main/java/com/example/sobok_android/presentation/view/home/HomeStickerBottomSheetFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PiilAddCalendarAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddBottomSheetFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFinishBottomSheetFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFinishFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFormDateFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFormFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFormNameFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/adapter/PillListAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/adapter/PillNameAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/adapter/PillTimeAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/viewmodel/PillAddViewModel.kt
  app/src/main/res/drawable/rectangle_border_darkmint_fill_lightmint_radius_6dp.xml
  app/src/main/res/drawable/rectangle_darkmint_border_6dp.xml
  app/src/main/res/layout/activity_pill_add.xml
  app/src/main/res/layout/fragment_pill_add_finish.xml
  app/src/main/res/layout/fragment_pill_add_finish_bottom_sheet.xml
  app/src/main/res/layout/fragment_pill_add_form.xml
  app/src/main/res/layout/fragment_pill_add_form_date.xml
  app/src/main/res/layout/fragment_pill_add_form_name.xml
  app/src/main/res/layout/item_pill_add_finish_name.xml
  app/src/main/res/layout/item_pill_add_finish_time.xml
  app/src/main/res/navigation/nav_pill_add.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: 🍎 채영, feat, 💊 약추가

#67 [FEAT] 설정 UI
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/SettingActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/SettingMainFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/SettingTermsOfUseFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/SettingWithdrawalFragment.kt
  app/src/main/java/com/example/sobok_android/util/ContextExt.kt
  app/src/main/java/com/example/sobok_android/util/CustomDialog.kt
  app/src/main/java/com/example/sobok_android/util/DialogUtil.kt
  app/src/main/res/drawable/ic_more_48_gray500.xml
  app/src/main/res/drawable/rectangle_fill_gray100_border_gray300_radius_12.xml
  app/src/main/res/drawable/rectangle_fill_white_radius_10.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_setting_main.xml
  app/src/main/res/layout/fragment_setting_terms_of_use.xml
  app/src/main/res/layout/fragment_setting_withdrawal.xml
  app/src/main/res/layout/generic_dialog.xml
  app/src/main/res/navigation/nav_setting.xml
  app/src/main/res/values/strings.xml
Labels: 🍋 수현, feat, UI

#71 Feature/61 my info/api
  app/src/main/java/com/example/sobok_android/data/api/MyInfoService.kt
  app/src/main/java/com/example/sobok_android/data/datasource/myinfo/MyInfoDataSource.kt
  app/src/main/java/com/example/sobok_android/data/datasource/myinfo/MyInfoRemoteDataSource.kt
  app/src/main/java/com/example/sobok_android/data/mapper/MyInfoMapper.kt
  app/src/main/java/com/example/sobok_android/data/model/request/myinfo/ReqMyNicknameData.kt
  app/src/main/java/com/example/sobok_android/data/model/response/ResGenericData.kt
  app/src/main/java/com/example/sobok_android/data/model/response/myinfo/ResMyPillData.kt
  app/src/main/java/com/example/sobok_android/data/repository/myinfo/MyInfoRepositoryImpl.kt
  app/src/main/java/com/example/sobok_android/domain/model/GenericData.kt
  app/src/main/java/com/example/sobok_android/domain/repository/myinfo/MyInfoRepository.kt
  app/src/main/java/com/example/sobok_android/presentation/di/DataSourceModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/NetworkModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/RepositoryModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/ViewModelModule.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/MyInfoActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/MyNicknameEditActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/viewmodel/MyInfoViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🍋 수현, feat, network

#72 [FEAT] 내 정보 & 닉네임 수정 base
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sobok_android/data/api/MyInfoService.kt
  app/src/main/java/com/example/sobok_android/data/datasource/myinfo/MyInfoDataSource.kt
  app/src/main/java/com/example/sobok_android/data/datasource/myinfo/MyInfoRemoteDataSource.kt
  app/src/main/java/com/example/sobok_android/data/mapper/MyInfoMapper.kt
  app/src/main/java/com/example/sobok_android/data/model/request/myinfo/ReqMyNicknameData.kt
  app/src/main/java/com/example/sobok_android/data/model/response/ResGenericData.kt
  app/src/main/java/com/example/sobok_android/data/model/response/myinfo/ResMyPillData.kt
  app/src/main/java/com/example/sobok_android/data/repository/myinfo/MyInfoRepositoryImpl.kt
  app/src/main/java/com/example/sobok_android/domain/model/GenericData.kt
  app/src/main/java/com/example/sobok_android/domain/model/myinfo/MyPillData.kt
  app/src/main/java/com/example/sobok_android/domain/repository/myinfo/MyInfoRepository.kt
  app/src/main/java/com/example/sobok_android/presentation/di/DataSourceModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/NetworkModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/RepositoryModule.kt
  app/src/main/java/com/example/sobok_android/presentation/di/SobokApplication.kt
  app/src/main/java/com/example/sobok_android/presentation/di/ViewModelModule.kt
  app/src/main/java/com/example/sobok_android/presentation/view/home/HomeFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/MyInfoActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/MyNicknameEditActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/adapter/MyPillManageAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/viewmodel/MyInfoViewModel.kt
  app/src/main/java/com/example/sobok_android/presentation/view/share/ShareNameEditActivity.kt
  app/src/main/java/com/example/sobok_android/util/CustomSnackBar.kt
  app/src/main/res/color/selector_double_check.xml
  app/src/main/res/drawable/ic_close_48_black.xml
  app/src/main/res/drawable/ic_more_48_black.xml
  app/src/main/res/drawable/ic_notice.xml
  app/src/main/res/drawable/ic_pencil_32_black.xml
  app/src/main/res/drawable/ic_setting_48_black.xml
  app/src/main/res/layout/activity_my_info.xml
  app/src/main/res/layout/activity_my_nickname_edit.xml
  app/src/main/res/layout/activity_share_name_edit.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_my_info_pill.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🍋 수현, feat

#74 Feature/64-setting/base
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/MyInfoActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/SettingActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/SettingMainFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/SettingTermsOfUseFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/myinfo/SettingWithdrawalFragment.kt
  app/src/main/java/com/example/sobok_android/util/CustomDialog.kt
  app/src/main/java/com/example/sobok_android/util/DialogUtil.kt
  app/src/main/res/drawable/ic_more_48_gray500.xml
  app/src/main/res/drawable/rectangle_fill_gray100_border_gray300_radius_12.xml
  app/src/main/res/drawable/rectangle_fill_white_radius_10.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_setting_main.xml
  app/src/main/res/layout/fragment_setting_terms_of_use.xml
  app/src/main/res/layout/fragment_setting_withdrawal.xml
  app/src/main/res/layout/generic_dialog.xml
  app/src/main/res/navigation/nav_setting.xml
  app/src/main/res/values/strings.xml
Labels: 🍋 수현, UI

#75 Fix/66 pil add logic
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/example/sobok_android/domain/model/pill/pilladd/PillInfo.kt
  app/src/main/java/com/example/sobok_android/domain/model/pill/pilladd/PillListData.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddActivity.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddBottomSheetFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFinishBottomSheetFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFinishFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFormDateFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFormFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/PillAddFormNameFragment.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/adapter/PillListAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/adapter/PillNameAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/adapter/PillTimeAdapter.kt
  app/src/main/java/com/example/sobok_android/presentation/view/pill/add/viewmodel/PillAddViewModel.kt
  app/src/main/res/color/selector_pill_add_date_text.xml
  app/src/main/res/drawable/ic_btn_check_small_40.xml
  app/src/main/res/drawable/ic_btn_check_small_mint_40.xml
  app/src/main/res/drawable/ic_close_48_dark_mint_main.xml
  app/src/main/res/drawable/ic_more_right_48_black.xml
  app/src/main/res/drawable/ic_plus_48_gray600.xml
  app/src/main/res/drawable/rectangle_border_darkmint_radius12dp.xml
  app/src/main/res/drawable/rectangle_fill_gray200.xml
  app/src/main/res/drawable/selector_pill_add_3month.xml
  app/src/main/res/drawable/selector_pill_add_date.xml
  app/src/main/res/drawable/selector_pill_add_next.xml
  app/src/main/res/layout/fragment_pill_add_bottom_sheet.xml
  app/src/main/res/layout/fragment_pill_add_finish_bottom_sheet.xml
  app/src/main/res/layout/fragment_pill_add_form.xml
  app/src/main/res/layout/fragment_pill_add_form_date.xml
  app/src/main/res/layout/fragment_pill_add_form_name.xml
  app/src/main/res/layout/item_pill_add_pill_info.xml
  app/src/main/res/layout/item_pill_add_pill_time.xml
  app/src/main/res/navigation/nav_pill_add.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🍎 채영, 💊 약추가
